/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chat;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;

/**
 *
 * @author jpari
 */
public class Client extends javax.swing.JFrame {
    
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dos;
    
    public Client() {
        initComponents();
        customizeUI();
    }

    private void customizeUI() {
        setTitle("WhatsApp Client");
        
        java.awt.Image wallpaperImage = null;
        javax.swing.ImageIcon avatarIcon = null;
        javax.swing.ImageIcon sendIcon = null;
        try {
            wallpaperImage = javax.imageio.ImageIO.read(Client.class.getResource("resources/background.png"));
            avatarIcon = new javax.swing.ImageIcon(Client.class.getResource("resources/avatar.png"));
            sendIcon = new javax.swing.ImageIcon(Client.class.getResource("resources/send.png"));
        } catch (Exception e) {
            System.err.println("Could not load resources: " + e.getMessage());
        }
        
        if (wallpaperImage != null) {
            ((javax.swing.JComponent) getContentPane()).setBorder(new ClientImageBackgroundBorder(wallpaperImage));
        } else {
            getContentPane().setBackground(new java.awt.Color(0xf0, 0xf2, 0xf5));
        }
        
        jLabel1.setOpaque(false);
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        jLabel1.setForeground(new java.awt.Color(0x00, 0x80, 0x69));
        jLabel1.setText("Server"); 
        if (avatarIcon != null) {
            jLabel1.setIcon(avatarIcon);
            jLabel1.setIconTextGap(8);
        }
        
        msg_area.setOpaque(false);
        msg_area.setForeground(new java.awt.Color(0x11, 0x1b, 0x21));
        msg_area.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        msg_area.setMargin(new java.awt.Insets(10, 12, 10, 12));
        msg_area.setLineWrap(true);
        msg_area.setWrapStyleWord(true);
        msg_area.setEditable(false);
        
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0xdd, 0xdd, 0xdd)));
        
        msg_text.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        msg_text.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0xcc, 0xcc, 0xcc), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10)
        ));
        msg_text.setBackground(java.awt.Color.WHITE);
        
        msg_send.setBackground(new java.awt.Color(0x00, 0x80, 0x69));
        msg_send.setForeground(java.awt.Color.WHITE);
        msg_send.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        if (sendIcon != null) {
            msg_send.setIcon(sendIcon);
            msg_send.setText("Send");
            msg_send.setIconTextGap(6);
        } else {
            msg_send.setText("Send");
        }
        msg_send.setFocusPainted(false);
        
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        msg_send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Client Chat");

        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        msg_send.setBackground(new java.awt.Color(204, 204, 204));
        msg_send.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msg_send.setText("Send");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(msg_text, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(msg_text))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:
        try{
            String msg;
            msg = msg_text.getText();
            dos.writeUTF(msg);
            msg_text.setText("");
            
        } catch (Exception e){
            
        }
        
    }//GEN-LAST:event_msg_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
        try{
            String msgIn = "";
            s = new Socket("127.0.0.1",1201);
            dis = new DataInputStream(s.getInputStream());
            dos = new DataOutputStream(s.getOutputStream());
            s.getOutputStream();
            while(!msgIn.equals("Exit")){
                msgIn = dis.readUTF();
                msg_area.setText(msg_area.getText() + "\n" + msgIn);
                
            }
        } catch(Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    private static javax.swing.JTextField msg_text;
    // End of variables declaration//GEN-END:variables
}

class ClientImageBackgroundBorder implements javax.swing.border.Border {
    private final java.awt.Image image;
    
    ClientImageBackgroundBorder(java.awt.Image image) {
        this.image = image;
    }
    
    public java.awt.Insets getBorderInsets(java.awt.Component c) {
        return new java.awt.Insets(0, 0, 0, 0);
    }
    
    public boolean isBorderOpaque() {
        return true;
    }
    
    public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
        if (image != null) {
            int iw = image.getWidth(c);
            int ih = image.getHeight(c);
            if (iw > 0 && ih > 0) {
                for (int tx = x; tx < x + width; tx += iw) {
                    for (int ty = y; ty < y + height; ty += ih) {
                        g.drawImage(image, tx, ty, c);
                    }
                }
            }
        }
    }
}
